### ISSUE TITLE
Workspace node_modules collision with default setup

### ISSUE THREAD

**Issue by EliSchleifer** [rules-proto-grpc/rules_proto_grpc#114]
Our workspace already has a yarn install call for "npm". It seems like this is standard, but this set of rules wants to use "js_modules", which then creates a compilation failure when building node rules

fail("All npm dependencies need to come from a single workspace. Found '%s' and '%s'." % (node_modules_root, possible_root))
Error in fail: All npm dependencies need to come from a single workspace. Found 'external/npm/node_modules' and 'external/js_modules/node_modules'.

Is there a reason why the few dependencies are all sourced from js_modules and not npm? Am I missing something in how our repo should be setup to support this correctly. 

yarn_install(
    name = "npm",
    package_json = "//:package.json",
    yarn_lock = "//:yarn.lock",
)

**Comment by aaliddell** [comment]
This was done historically to match how these rules work for other langauges, whereby a `lang_proto_library` will give you a library with all the transitive dependencies for the specific grpc and protobuf versions correctly bundled in. Curiously this error hasn't been present until it's appeared twice in the last 24 hrs, see comments in #113. It looks like the logic for raising that error changed recently in rules_nodejs, but I don't see why it was working previously though, perhaps it didn't :thinking: 

As it stands, it looks like we'll have to drop the `@js_modules` repo and expect the user to add the necessary dependencies to their own `package.json` and that it's named @npm. This is going to a be less user friendly, since the error messages will be a lot more cryptic and the setup of rules_proto_grpc will be more than just WORKSPACE additions, but seems necessary to prevent overlapping duplicate packages.

In the meantime, you can use `js_proto_compile` and feed the outputs to your own `js_library` that has the dependencies coming from `@npm`.

**Comment by EliSchleifer** [comment]
Thanks will do.

**Comment by slapierre** [comment]
@aaliddell - do you have a recommendation / temporary workaround for folks consuming the generated code with `ts_project` / `ts_library`?

-- thanks!

**Comment by EliSchleifer** [comment]
As a workaround for now you can just write rules as such in your own repo

load("@rules_proto_grpc//js:js_proto_compile.bzl", "js_proto_compile")
load("@rules_proto_grpc//internal:compile.bzl", "proto_compile_attrs")
load("@build_bazel_rules_nodejs//:index.bzl", "js_library")

def js_proto_library(name, package_name = None, **kwargs):
    # Compile protos
    js_proto_compile(
        name = name,
        **{
            k: v
            for (k, v) in kwargs.items()
            if k in ["protos" if "protos" in kwargs else "deps"] + proto_compile_attrs.keys()
        }  # Forward args
    )

    # Create js library
    js_library(
        name = name + "_lib",
        srcs = [name],
        deps = PROTO_DEPS + (kwargs.get("deps", []) if "protos" in kwargs else []),
        package_name = package_name,
        visibility = kwargs.get("visibility"),
        tags = kwargs.get("tags"),
    )

PROTO_DEPS = [
    "@npm//google-protobuf",
]

**Comment by aaliddell** [comment]
Please take a look at the [typescript test workspace on the dev branch](https://github.com/rules-proto-grpc/rules_proto_grpc/tree/dev/test_workspaces/typescript); this is how it is going to have to be necessary to load deps in 3.1.0 and there is an attr to specify something other than `@npm` if you aren't using that. The same concept will apply to the pure JS rules, whether you are using TS or not. Regrettably this will require users to update their WORKSPACE *again*, but I can't see an alternative that works :disappointed: 

rules_nodejs introduced nested node_modules in 3.0.0, but unfortunately these aren't suitable for the use-case here (after much head-scratching to see if there was a workaround).

If you have any feedback on that, let me know.

**Comment by pshields** [comment]
FWIW, personally, I don't mind placing the transitive dependencies for these gRPC JS rules in `package.json` on my projects, although I can appreciate the desire to be consistent across languages for whether or not those dependencies are automatically packaged in with the rules. I would favor proceeding with the changes in #115 over waiting for a potentially cleaner approach.
