### ISSUE TITLE
Broken proto dependency in grpc_ecosystem_grpc_gateway

### ISSUE THREAD

**Issue by luna-duclos** [rules-proto-grpc/rules_proto_grpc#119]
When using the Go rules, I get the following issue: 

```
internal/descriptor/apiconfig/apiconfig.proto: google/api/http.proto is imported, but @grpc_ecosystem_grpc_gateway//internal/descriptor/apiconfig:apiconfig_proto doesn't directly depend on a proto_library that 'srcs' it.
```

**Comment by aaliddell** [comment]
Do you have an example failing example?

At first glance, it appears that your `apiconfig_proto` `proto_library` target is missing a direct dependency on `@go_googleapis//google/api:http_proto`

**Comment by luna-duclos** [comment]
This seems to happen in every case I try. The issue seems to be in the upstream `grpc_ecosystem_grpc_gateway` repo that is used as a dependency of this one.

if you check the upstream repo: https://github.com/grpc-ecosystem/grpc-gateway/blob/master/internal/descriptor/apiconfig/BUILD.bazel

This file is whats missing the `@go_googleapis//google/api:http_proto` dependency

**Comment by aaliddell** [comment]
Ok, gotcha. What's odd is that I can't recreate that, even with an explicit `--strict_proto_deps=strict`, which I believe is what is driving this error via Bazel's invocation of protoc and should be enabled by default anyway. It certainly appears that target should be breaking the strict deps rule, but I can't get it to complain.

Do you have anything protoc specific in your `.bazelrc`? Otherwise a minimal repro would be very useful.

In the short term, `--strict_proto_deps=off` (or warn) might help you bypass the error, until the required dep is added to grpc-gateway upstream.

**Comment by luna-duclos** [comment]
Yeah, I cant reproduce it super minimally either, its likely caused by something more complex in our large monorepo that I can't quite spot in an isolated case

**Comment by luna-duclos** [comment]
For now I've manually patched it via a patch in our monorepo's workspace until the fix is upstream in : https://github.com/grpc-ecosystem/grpc-gateway/

**Comment by aaliddell** [comment]
Ok, so see https://github.com/bazelbuild/bazel/issues/13208#issuecomment-797102055

Depending on how you load `go_googleapis` you will get two different definitions of `annotations_proto`, one of which will cause the error and one of which wont :exploding_head:

So unfortunately I don't there's anything I can solve in this repo, since it's either a problem in `rules_go` (for running a patched `go_googleapis`) or a problem in grpc-gateway (for depending on a non-standard `go_googleapis`). Since `go_googleapis` already has Bazel targets defined, I'm not really sure why `rules_go` uses Gazelle there in the first place to rewrite the targets.

**Comment by luna-duclos** [comment]
Oof, thats incredibly annoying alright ... It seems the most reasonable thing to do is to patch it upstream then, I will see what I can do there ... the upstream repos are usually incredibly slow to take PRs so I'm not particularly hopeful

**Comment by aaliddell** [comment]
Closing since there's nothing that can be done within the scope of this repo to resolve this, since it's dependent on the rules_go behaviour. It is a useful documentation for anyone hitting the same problem though.
