### ISSUE TITLE
go_proto_compile produces executable .pb.go file

### ISSUE THREAD

**Issue by noel-yap** [rules-proto-grpc/rules_proto_grpc#159]
### Description

I'm not sure if this is a bug, intentional, or something else. When a `.pb.go` file is produced by  a `go_proto_compile` target, the file is executable. If this is a bug or unintentional, I wanted to bring it to attention so it can be fixed. If it's intentional, I'd like to understand the rationales behind it.

**Comment by aaliddell** [comment]
I don’t think this is intentional, but is it causing a problem with having them executable? For go_proto_compile we don’t actually touch the outputs that protoc gives us, besides shuffling them around. So does running protoc without Bazel give executable or non-executable go files?

Something in the back of my mind is saying there’s a Bazel specific gotcha here, but I’d need to check that.

**Comment by noel-yap** [comment]
No, it's not causing any problems that I've seen so far, but the paranoid in me would prefer minimal permissions being set on files in general.

**Comment by aaliddell** [comment]
> Something in the back of my mind is saying there’s a Bazel specific gotcha here, but I’d need to check that.

Here is what I was remembering: https://github.com/bazelbuild/bazel/issues/6530#issuecomment-433502740

Effectively all files in the Bazel output tree are generally executable and this is working as-designed. So I will close this as it is not related to the rules in this repo, but rather a Bazel specific behaviour.
