### ISSUE TITLE
undefined: grpc.SupportPackageIsVersion7

### ISSUE THREAD

**Issue by noel-yap** [rules-proto-grpc/rules_proto_grpc#160]
### Description

When building, I'm getting the following errors:
```
example_grpc.pb.go:15:11: undefined: grpc.SupportPackageIsVersion7
example_grpc.pb.go:27:5: undefined: grpc.ClientConnInterface
example_grpc.pb.go:30:26: undefined: grpc.ClientConnInterface
example_grpc.pb.go:93:30: undefined: grpc.ServiceRegistrar
```

Some of the answers in https://stackoverflow.com/questions/63662787/undefined-grpc-supportpackageisversion7-grpc-serviceregistrar indicate version mismatches but I was under the impression that the `bazel` rules were supposed to help ensure those were compatible. Is my mental model inaccurate?

**Comment by aaliddell** [comment]
Do you have an example of code that reproduces this?

It looks to me that you are attempting to link a version of grpc that differs from the version used to generate the sources with protoc. Using `go_grpc_library` should prevent this from happening, since it uses the same exact version for both building and linking. However, I note in your other issue that you are using the `*_compile` rule, which suggests you are manually linking grpc instead?

**Comment by aaliddell** [comment]
So this is an issue with Gazelle 0.24.0, where they've added a super old version of gRPC to their dependencies, which then breaks all later declarations of `org_golang_google_grpc` and other dependencies: https://github.com/bazelbuild/bazel-gazelle/issues/1115

Example of broken CI when updating to Gazelle 0.24.0: https://buildkite.com/bazel/rules-proto-grpc-rules-proto-grpc/builds/1264#40146824-6b87-4b46-9e48-f4f8418555c3

Since it looks like they won't revert pulling in half the world just to run Gazelle, we'll have to work around it and have a breaking change note in our docs.
