### ISSUE TITLE
[Feature Request] Make the protobuf runtime dependency customizable?

### ISSUE THREAD

**Issue by dnkoutso** [rules-proto-grpc/rules_proto_grpc#197]
### Description

The provided macros such as `objc_proto_library` force the usage of "@com_google_protobuf//:protobuf_objc" dependency [here](https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/objc/objc_proto_library.bzl#L54).

Believe it or not we have a fork of the Protobuf runtime in our organization for a few improvements we have not yet upstreamed (if ever). 

It would be nice if this was possible to be customized and parameterized for us to be able to provide our own protobuf runtime.

Thanks!

**Comment by aaliddell** [comment]
This is a very niche use case, as I don't think too many people have a forked copy of protobuf. So I am hesitant to add complexity for this.

However, you could either alias your forked protobuf repo into the `com_google_protobuf` name, or otherwise you can have a local copy of [objc_proto_library.bzl](https://github.com/rules-proto-grpc/rules_proto_grpc/blob/2e8be8e27cc82203794f14dbdcf37189b02ab722/objc/objc_proto_library.bzl#L53-L55) that has a different value of `PROTO_DEPS`.

**Comment by dnkoutso** [comment]
> otherwise you can have a local copy of [objc_proto_library.bzl](https://github.com/rules-proto-grpc/rules_proto_grpc/blob/2e8be8e27cc82203794f14dbdcf37189b02ab722/objc/objc_proto_library.bzl#L53-L55) that has a different value of PROTO_DEPS.

yeap we ended up doing this.

Thanks again for the response. I think that makes sense.
