### ISSUE TITLE
Publish documentation for proto_plugin, ProtoPluginInfo, proto_compile_attrs, proto_compile_impl

### ISSUE THREAD

**Issue by gonzojive** [rules-proto-grpc/rules_proto_grpc#225]
### Description

In trying to implement a custom Typescript rule (https://github.com/aspect-build/rules_js/issues/397), I found the ["Custom Plugins" documentation](https://rules-proto-grpc.com/en/latest/custom_plugins.html) too high level and wanted API docs.

This isn't really the fault of the library authors. Starlark documentation is in general pretty hard to navigate compared to godoc. Most of the things I care about have docstrings: https://github.com/rules-proto-grpc/rules_proto_grpc/blob/master/internal/compile.bzl#L44 for example.

**Comment by aaliddell** [comment]
Hi, since you've just been 'new' to the docs, you have a perspective I perhaps don't. What would be useful to add to the docs in particular that you felt you had to dive into the code for? Does the detail in the docstrings suffice or is there more that your had to figure out manually?

**Comment by gonzojive** [comment]
The detail in the docstrings is pretty good, especially when paired with the documentation articles on the web site. Examples are good because they show how the pieces work together.

**Comment by gonzojive** [comment]
To summarize, publishing API-style generated documentation for the `proto_plugin, ProtoPluginInfo, proto_compile_attrs, proto_compile_impl` is what I'd like to see for this bug.

**Comment by aaliddell** [comment]
Ok, I have added and improved docs for ``proto_plugin`` in #227 ([commit](https://github.com/rules-proto-grpc/rules_proto_grpc/pull/227/commits/71b47729cdf856808f5db8ecd4db8cb2f348682a)), but the others have some issues:

-  The fields in ``proto_compile_attrs`` are already documented in every language rule, such as here: https://rules-proto-grpc.com/en/latest/lang/cpp.html#attributes
- ``ProtoPluginInfo`` is an internal implementation detail that isn't expected to be used externally even by custom plugin authors, since it is created by ``proto_plugin``. It's exported in defs.bzl but I really don't remember why...
- ``proto_compile_impl`` only has one arg, which is the standard ``ctx`` object given by Bazel
