### ISSUE TITLE
Error referencing proto_common_do_not_use in java rules in 4.3.0

### ISSUE THREAD

**Issue by alex-shinn** [rules-proto-grpc/rules_proto_grpc#230]
### Issue Description

The java examples build fine in 4.2.0:

```
$ git co 4.2.0
$ bazel build example/java/...
...
INFO: Analyzed 15 targets (128 packages loaded, 2513 targets configured).
INFO: Found 15 targets...
INFO: Elapsed time: 553.547s, Critical Path: 87.74s
INFO: 330 processes: 22 internal, 291 linux-sandbox, 17 worker.
INFO: Build completed successfully, 330 total actions
```

however with 4.3.0 we get the following error complaining that proto_common_do_not_use is undefined:

```
$ git co 4.3.0
Previous HEAD position was c1f2c3f5 Merge branch 'dev'
HEAD is now at 5c279495 Merge pull request #227 from rules-proto-grpc/dev
$ bazel build example/java/...
...
ERROR: /home/alex_shinn/.cache/bazel/_bazel_alex_shinn/5777455a3893fa058a674654c2e2378d/external/rules_proto/proto/private/native.bzl:28:23: name 'proto_common_do_not_use' is not defined
ERROR: error loading package 'example/java/java_grpc_compile': at /home/alex_shinn/src/rules_proto_grpc.upstream/java/defs.bzl:3:6: at /home/alex_shinn/src/rules_proto_grpc.upstream/java/java_proto_compile.bzl:4:5: at /home/alex_shinn/src/rules_proto_grpc.upstream/defs.bzl:4:6: at /home/alex_shinn/src/rules_proto_grpc.upstream/internal/compile.bzl:3:6: at /home/alex_shinn/.cache/bazel/_bazel_alex_shinn/5777455a3893fa058a674654c2e2378d/external/rules_proto/proto/defs.bzl:17:6: compilation of module 'proto/private/native.bzl' failed
INFO: Elapsed time: 18.535s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: example/java/java_grpc_compile
    Fetching @rules_java; fetching
    Fetching ...s_java; Extracting /home/alex_shinn/.cache/bazel/_bazel_alex_shinn/5777455a3893fa058a674654c2e2378d/external/rules_java/temp7463346105659584946/385292fcfd244186e5e5811122ed32cf214a9024.tar.gz
```

This appears to come from a recent change in rules_proto: https://github.com/bazelbuild/rules_proto/blame/master/proto/private/native.bzl#L28

### rules_proto_grpc Version

4.3.0

### Bazel Version

5.3.0

### OS

Linux vm-ashinn 5.15.0-1016-gcp #21~20.04.1-Ubuntu SMP Fri Aug 5 12:53:07 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Link to Demo Repo

https://github.com/rules-proto-grpc/

**Comment by aaliddell** [comment]
Hmm, so if I do the exact same sequence of steps I get no build failure on Bazel 5.3.2 under Ubuntu 22.04:

```
git checkout 4.3.0
bazel build example/java/... 
                                                                                                                                                                                                                 
INFO: Analyzed 15 targets (0 packages loaded, 0 targets configured).
INFO: Found 15 targets...
INFO: Elapsed time: 1.290s, Critical Path: 0.00s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
```

If I use bazelisk to get Bazel 5.3.0 I also get a successful build. However, if I step back to Bazel 5.2.0 I then get the same build failure as you see, so it seems you are somehow using an older Bazel version than you expect.

For a fix on my side, there's two options:
- Rollback the `rules_proto` version to before that `proto_common_do_not_use` change landed.
- Update the `MINIMUM_BAZEL_VERSION` in these rules to 5.3.0. This is the more likely option to implemented, since Bazel 6 is just around the corner.

For your side, you have a few options until the above happens:
- Update Bazel to 5.3.0
- Rollback `rules_proto_grpc` to 4.2.0
- Override the version of `rules_proto` in your `WORKSPACE` file prior to loading `rules_proto_grpc` 4.3.0

**Comment by alex-shinn** [comment]
Yes, indeed, I was using bazel 5.2.0.  Sorry about that, it was a typo.

I upgraded to 5.3.2 and it works fine.  Updating the `MINIMUM_BAZEL_VERSION` should suffice.
