### ISSUE TITLE
What is the real difference between compile and library?

### ISSUE THREAD

**Issue by yeukhon** [rules-proto-grpc/rules_proto_grpc#278]
### Description

For example, I was generating proto with `python_proto_compile` and `python_proto_library` and they both generate the same `pb2.py` file.

I am not sure if I really understand the differnce based on the doc:

> python_proto_compile | Generates Python protobuf .py files
> python_proto_library | Generates a Python protobuf library using `py_library` from `rules_python`

**Comment by aaliddell** [comment]
The compile rules will simply run protoc on the inputs and return the output files; it's then up to you to integrate these files into your build with the correct prefixes.

The library rules take the files from protoc and wrap them in a py_library target that has the import path setup etc, so that your py_binary targets can directly depend on this library.

**Comment by aaliddell** [comment]
Yep 👍
