### ISSUE TITLE
Public headers must be in `hdrs`, not `srcs`.

### ISSUE THREAD

**Issue by Monnoroch** [rules-proto-grpc/rules_proto_grpc#40]
Currently generated proto headers for C/C++ are in `srcs` ([code](https://github.com/rules-proto-grpc/rules_proto_grpc/blob/8c8aab86c761ba762477128f121e12974e14b497/cpp/cpp_proto_library.bzl#L14)). Since these are supposed to be "public" headers, this is incorrect. See [documentation](https://docs.bazel.build/versions/master/be/c-cpp.html#hdrs) for explanation.

> Headers in srcs must only be directly included from the files in hdrs and srcs of the library itself.

The current implementation works by accident because Bazel doesn't enforce the distinction between public and private headers.

**Comment by aaliddell** [comment]
The fix for this is linked to #25, whereby the C++ rules need to create CcInfo providers that can interact with the normal C++ compilation process. Presently `cpp_*_library` is just a macro over `cc_library`, which means it cannot see the generated files and therefore cannot split the outputs between `srcs` and `hdrs` based on extension.

**Comment by aaliddell** [comment]
This will be addressed in 3.0.0 #106, where hdrs and srcs are now split to the correct attrs
