### ISSUE TITLE
Adding 'Options'?

### ISSUE THREAD

**Issue by amit-traiana** [rules-proto-grpc/rules_proto_grpc#54]
Is there a way to add 'Options' to a plug-in without modifying the project's BUILD file? Passing it as argument when defining the rule? was thinking about something like that:

```
scala_grpc_compile(
    name = "test",
    options = [
            "java_conversions",
            "grpc",
        ],
    deps = [":testl_proto"],
)
```

We need to use `java_conversions` here, but I'm not completely OK with adding it to the scala BUILD file, as while it's very popular, not all user will want to use it.

Thanks.

**Comment by aaliddell** [comment]
There used to be a similar option in the original rules_proto, but it was removed when moving to aspect based compilation. It's been a while since I looked at exactly why, but IIRC it is to do with aspects only being able to see string arguments. So it would have to become one of the following two options:

- Pass an `options_string` parameter to `scala_grpc_compile` with the options pre-merged by the user.
- Convert the options list given above into an options string in the `scala_grpc_compile` wrapper macro, much like we currently do with the `verbose` option here: https://github.com/rules-proto-grpc/rules_proto_grpc/blob/627741e7c310ebc316d85a4843ddca5b7604ca77/scala/scala_proto_compile.bzl#L47-L52

The second would be nicer, as users wouldn't need to know how to merge the options. The current 'recommendation' (which I agree sucks) is to copy and update the plugin definition to your local workspace and then also copy the relevant `.bzl` file locally to update the plugin path.

**Comment by amit-traiana** [comment]
Second option would be nicer indeed. The problem is that unlike `verbose_string` that has a defined sets of arguments (0, None, 1, 2, 3 ,4), `options_string` will never have a predefined set of options - because each plug-in supports it own options.

If I'm following the `verbose_string` example, it accessable in `proto_compile_aspect_impl` because it's defined in `proto_compile_aspect_attrs`. I can't define `options_string` in `proto_compile_aspect_attrs`, because it need a specific set of `values` (being an aspect attribute). Got an idea how to pass that information to `proto_compile_aspect_impl` (the plugin options string is being built there).

**Comment by aaliddell** [comment]
Ahh, that’s the bit I was forgetting and the reason the option was dropped. In which case, there’s not a lot we can do to improve the situation until aspects are allowed more freedom with arguments. See https://github.com/bazelbuild/bazel/issues/8494

You may be able to put the attr on the target, but again there may be issues with that route the I’m not remembering.

**Comment by amit-traiana** [comment]
It's a problem only with public attributes. I can easily set `_options_string` but `options_string` require `values`. 

> You may be able to put the attr on the target

What do you mean by that? the `rule()` definition? because it means I will be able to access it from `proto_compile_impl()`, but the plug-in options string is being defined and the plug-in runs on ` proto_compile_aspect_impl` - and I can't access the attr from there. 

> The current 'recommendation' (which I agree sucks) is to copy and update the plugin definition to your local workspace and then also copy the relevant .bzl file locally to update the plugin path.

It's a bit more complex than that if I understand correctly? the rule is being referenced in the build file like so:

`load("@rules_proto_grpc//scala:defs.bzl", "scala_grpc_compile")`

It means that I have to own a copy of `defs.bzl`, modify `load(":scala_grpc_compile.bzl", _scala_grpc_compile="scala_grpc_compile")` to pin into my own `scala_grpc_compile.bzl` file, and also create my own `scala/BUILD` file so get the options from? 
I'm considering maybe to Fork instead and just change the 'options'. It will also let me the options to control the dependencies versions, but It means I'll have to constantly merge. 


plugin definition would be the BUILD file in the `scala` folder and the relevant .bzl file will be the `scala_grpc_compile.bzl`? I wonder

**Comment by aaliddell** [comment]
Added as part of upcoming 3.0.0: #106

You can now do:

```starlark
python_proto_compile(
    name = "person_python_proto",
    protos = ["@rules_proto_grpc//example/proto:person_proto"],
    options = {
        "@rules_proto_grpc//python:python_plugin": ["some_opt"],  # <- Applies to specific plugin
    }
)
```
 or

```starlark
python_proto_compile(
    name = "person_python_proto",
    protos = ["@rules_proto_grpc//example/proto:person_proto"],
    options = {
        "*": ["some_opt"],  # <- Applied to all plugins in rule
    }
)
```
