### ISSUE TITLE
META: Is this project live? Does it need help?

### ISSUE THREAD

**Issue by crutcher-dunnavant-techlabs** [rules-proto-grpc/rules_proto_grpc#76]
This project looks very useful; but it also appears to have stalled in the early part of this year.

Does it need help?

**Comment by aaliddell** [comment]
The project is still live and works with current Bazel version (as much as it worked with previous Bazel anyway), but needs a decent amount of work to update all the dependencies and fix a few outstanding bugs. Unfortunately I haven't had the time to devote to this since March, but haven't forgotten about it!

**Comment by aaliddell** [comment]
New release coming tomorrow (or thereabouts)
